//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace UniversityManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [Key]
        public int UserId { get; set; }
       
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        
        
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        
        [Display(Name = "Email Address")]
        public string Email { get; set; }
        
        [Display(Name = "Mobile Number")]
        public string Mobile { get; set; }
    }
}
